version: '3.4'

services:
  SSO-BASE:
    image: sso-base
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "2000:80"
networks:
  default:
    external:
      name: rede-integrada