version: '3.4'

services:
  SSO-BASE:
    image: sso-base
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
      - "80:80"
networks:
  default:
    external:
      name: rede-integrada