version: '3.4'

services:
  SSO-BASE:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    image: sso-base
    build:
      context: API/.
      dockerfile: dockerfile
    ports:
      - "2000:80"
networks:
  default:
    external:
      name: rede-integrada