version: '3.4'

services:
  weatherforecast:
    image: SSO-BASE
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
networks:
  default:
    external:
      name: rede-integrada